name: Build Website with TypeDoc and Examples
on:
    release:
        types: [created]
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - run: npm ci

            - name: Build Docs
              run: npm run docs
            - name: Create Public Folder
              run: |
                  mkdir public
                  mkdir public/docs
                  mkdir public/examples
            - name: Copy Docs to Public
              run: mv docs/* public/docs
            - name: Copy Examples to Public
              run: mv examples/* public/examples

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
